#!/bin/ksh

###############################
# Escrito en mexico!!!        #
# escrito el 22/01/2013 por:  #
#        Pedro Amezquita      #
# juan_amezquita@xyratex.com  #
###############################
txtvrd="\\033[1;32m"   # Verde
txtamr="\\033[1;33m"   # Amarillo
txtazl="\\033[1;36m"   # Azul claro
txtbnc="\\033[1;37m"   # Blanco
txtroj="\\033[1;31m"   # Rojo
txtbnk="\\033[5m" 
txtbno="\\033[25m"
menuopts=5


#********************************Drivers******************************************


echo "${txtazl}Instalando modulos por favor espera..."
modprobe ipmi_si
modprobe ipmi_devintf
modprobe sg
modprobe mpt2sas







#*************************************************-MENU-********************************************************************
 while :
do

clear
echo ""
echo " ${txtamr}******Elimina encriptacion en discos HILF ${txtroj}${txtbnk}(Willy favor de no borrar)${txtbnc}******${txtbno}"
echo ""
echo " ${txtbnc}1. ${txtazl}Muestra SED en HDDs...................................${txtbnc}*"
echo " ${txtbnc}2. ${txtazl}Elimina encriptacion..................................${txtbnc}*"
echo " ${txtbnc}3. ${txtazl}Limpiar SEL...........................................${txtbnc}*"
echo " ${txtbnc}4. ${txtazl}Apagar UUT............................................${txtbnc}*"
echo " ${txtbnc}5. ${txtazl}Salir.................................................${txtbnc}*"
 echo -n "seleccione la opcion deseada[${txtvrd}1 ${txtbnc}- ${txtvrd}${menuopts}${txtbnc}]"
  read opt
 case $opt in

1)   echo ""
     echo "${txtazl}Validabdo SED..."
     sed_configure_tc_sg -adpt=mpt2sas -adpn=0xa000 -bus=0 -id=0x110  -display_only
     echo "${txtbnc}Presione [${txtazl}Enter${txtbnc}] para continuar. . .";     
     read enterKey;;

2)   echo ""
     echo "${txtazl}Eliminando encriptacion SED..."
     ./SED_EraseBand.sh
     ipmitool sel clear
     echo "${txtbnc}Presione [${txtazl}Enter${txtbnc}] para continuar. . .";  
     read enterKey;;

3)   echo ""
     echo "${txtazl}Apagando UUT..."
     ipmitool sel clear
     echo "${txtbnc}Presione [${txtazl}Enter${txtbnc}] para continuar. . .";
     read enterKey;;    
     
4)   echo ""
     echo "${txtazl}Limpiando SEL..."
     shutdown -h now
     echo "${txtbnc}Presione [${txtazl}Enter${txtbnc}] para continuar. . .";
     read enterKey;;
     
5)   echo ""
     clear
     echo "${txtamr}Written by Pedro Amezquita, Tanks for using Mexican software!!!${txtbnc}" ;
     sleep 2s
     clear
     exit 1;;

esac
done
